---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment-dev
  namespace: development
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment-stg
  namespace: staging
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent-container
        image: httpd:latest
        ports:
        - containerPort: 80
